#!/usr/bin/env bash
#python3 train_supcon.py --data_dir ../Data/TFRecord_w29_s15/1/ --batch_size 4096 --window_size 29 --cosine --print_freq 100 --mode cnn --gpu_device 0 --learning_rate 0.1 --learning_rate_classifier 0.5 --num_workers 4 --epochs 200 --save_freq 5
batch_size_choice=(512 1024 2048 4096 6000)
num_workers=2
epochs=200
learning_rate=0.5
learning_rate_classifier=1.0

for batch_size in "${batch_size_choice[@]}"; do
    args="--data_dir ../Data/TFRecord_w29_s15/1/ --window_size 29 --cosine --print_freq 100 --mode cnn --save_freq 5 --learning_rate "$learning_rate" --learning_rate_classifier "$learning_rate_classifier" --num_workers "$num_workers" --epochs "$epochs" --batch_size "$batch_size
    cmd="python3 train_supcon.py "$args" &"
    eval $cmd
done